### PR TITLE
Fix selected pin not visible on mobile

### LINKED ISSUE #592: [Map] Selected pin is hidden under building details on mobile
**Description:** In mobile version when selecting a building on map by click on it, the map zooms, the building info panel appears over the selected pin. The user can not see any more where where is placed the building on map while it read info about it.

**Steps to reproduce:**
1. Open the home page in Chrome Dev Tools and select mobile view.
2. Chose any mobile screen (iPhone, S5, any...)
3. Click on a building marker.

**Actual outcome:**

Map centers and the pin is hidden under info panel. 

image

**Expected outcome:**

On mobile version the map should focus the selected marker some where so it can be visible when info panel rendes.

image

### PR DESCRIPTION
**Pull request by annacs94**
### What does it fix?

Closes #592

- the right panel displaying building details and search results takes up the full width on mobile 
- drawer component has been removed, replaced with a grid based solution that enabled centering the map on the selected pin correctly; also map controls are not covered anymore
- fixed i18n warnings in client tests

### How has it been tested?

- tested manually

### CODE REVIEW

File: client/src/components/BuildingDetails.js [hunk 1]
```diff
@@ -1,39 +1,37 @@
...
       {details ? (
         <div>
           <Row>
             <Col lg={{ span: 13, offset: 2 }} span={13}>
               <Trans>Address</Trans>:
             </Col>
-            <Col lg={9} span={11}>
-              {details.address} <Trans>no.</Trans> {details.post_code}
-            </Col>
+            {details.address && details.post_code && (
```
Comment (cipick) [inline client/src/components/BuildingDetails.js:30]: do we want to still show the `address` but only hide "no." text if the `post_code` is `null`?
```suggestion
{details.address} {details.post_code && <Trans>no.</Trans>} {details.post_code}
```

Comment (annacs94) [reply client/src/components/BuildingDetails.js]: Initially I have added the null check, because while the details were loading the "no." text appeared in the middle of nowhere (see attached image). I don't know if `post_code` is a required field or not though, so I have added the separate check, as you suggested. :)

Screenshot 2021-03-20 at 21 19 12

**Review by tudoramariei — APPROVED** [review]
